services:
  api:
    container_name: go-api
    build:
      context: .
      dockerfile: Dockerfile
    image: go-api
    ports:
      - 8080:8080
    env_file:
      - .env.example
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_URI=redis:6379
    networks:
      - go-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

  mongo:
    container_name: go-mongodb
    image: mongo:8.0.0
    volumes:  
      - mongodbdata:/data/db
    networks:
      - go-network
    healthcheck:
      test: ["CMD", "pgrep", "mongod"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  redis:
    container_name: go-redis
    image: redis:7.4
    volumes:
      - redisdata:/data
    networks:
      - go-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
volumes:
  mongodbdata:
  redisdata:

networks:
  go-network:
    driver: bridge
