version: "3.9"

services:
  api:
    container_name: go-api
    build:
      context: .
      dockerfile: Dockerfile
    image: go-api
    ports:
      - 8080:8080
    environment:
      - MONGO_URI=mongodb://db:27017
      - MONGO_DB=opensource
      - MONGO_COLLECTION=contributors
      - PORT=8080
      - BASIC_AUTH_USERNAME=opensource
      - BASIC_AUTH_PASSWORD=greensquare
    depends_on:
      - db  
    networks:
      - go-network

  db:
    container_name: go-mongodb
    image: mongo:6.0
    volumes:  
      - dbdata:/data/db
    networks:
      - go-network

volumes:
  dbdata:

networks:
  go-network:
    driver: bridge