version: "3.9"

services:
  api:
    container_name: go-api
    build:
      context: .
      dockerfile: Dockerfile
    image: go-api
    ports:
      - 8088:8088
    env_file:
      - .env.docker
  database:
    container_name: go-mongodb
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:  
      - dbdata:/data/db

volumes:
  dbdata:
