package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.50

import (
	"context"
	"fmt"

	"github.com/Pradumnasaraf/Contributors/database"
	"github.com/Pradumnasaraf/Contributors/graph/model"
)

var db = database.NewMongoDB()

// AddAContributor is the resolver for the addAContributor field.
func (r *mutationResolver) AddAContributor(ctx context.Context, input model.NewContributor) (*model.Contributor, error) {
	newContributor := &model.Contributor{
		UserID:         fmt.Sprint("U" + input.GithubUsername),
		Name:           input.Name,
		Email:          input.Email,
		GithubUsername: input.GithubUsername,
	}

	if input.Contributions != nil {
		newContributor.Contributions = []*model.Contribution{
			{
				ContributionID: fmt.Sprint("C" + input.Contributions.ProjectName),
				ProjectName:    input.Contributions.ProjectName,
				Type:           input.Contributions.Type,
				Date:           input.Contributions.Date,
			},
		}
	} else {
		newContributor.Contributions = []*model.Contribution{}
	}

	err := db.Add(newContributor)

	if err != nil {
		return nil, err
	}

	return newContributor, nil
}

// UpdateAContributor is the resolver for the updateAContributor field.
func (r *mutationResolver) UpdateAContributor(ctx context.Context, userID string, input model.UpdateContributor) (*model.Contributor, error) {
	updateContributor := &model.Contributor{
		UserID:         userID,
		Name:           input.Name,
		Email:          input.Email,
		GithubUsername: input.GithubUsername,
	}

	err := db.UpdateByID(updateContributor)
	if err != nil {
		return nil, err
	}

	return updateContributor, nil
}

// DeleteAContributor is the resolver for the deleteAContributor field.
func (r *mutationResolver) DeleteAContributor(ctx context.Context, userID string) (*model.Contributor, error) {
	err := db.DeleteByID(userID)
	if err != nil {
		return nil, err
	}
	return &model.Contributor{UserID: userID}, nil
}

// DeleteAContribution is the resolver for the deleteAContribution field.
func (r *mutationResolver) DeleteAContribution(ctx context.Context, userID string, contributionID string) (*model.Contribution, error) {
	err := db.DeleteContributionByID(userID, contributionID)
	if err != nil {
		return nil, err
	}
	return &model.Contribution{ContributionID: contributionID}, nil
}

// AddAContribution is the resolver for the addAContribution field.
func (r *mutationResolver) AddAContribution(ctx context.Context, userID string, input model.NewContribution) (*model.Contribution, error) {
	newContribution := &model.Contribution{
		ContributionID: fmt.Sprint("C" + input.ProjectName),
		ProjectName:    input.ProjectName,
		Type:           input.Type,
		Date:           input.Date,
	}

	err := db.AddContributionByID(userID, newContribution)
	if err != nil {
		return nil, err
	}

	return newContribution, nil
}

// GetAllContributors is the resolver for the getAllContributors field.
func (r *queryResolver) GetAllContributors(ctx context.Context) ([]*model.Contributor, error) {
	contributors, err := db.GetAll()
	if err != nil {
		return nil, err
	}

	return contributors, nil
}

// GetAContributor is the resolver for the getAContributor field.
func (r *queryResolver) GetAContributor(ctx context.Context, userID string) (*model.Contributor, error) {
	contributor, err := db.GetByID(userID)
	if err != nil {
		return nil, err
	}
	return contributor, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.

