apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless-service
spec:
  clusterIP: None # Headless service
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017