// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Contributor struct {
	ID             string `json:"id" bson:"_id"`
	GithubUsername string `json:"githubUsername"`
	Name           string `json:"name"`
	Email          string `json:"email"`
}

type NewContributor struct {
	GithubUsername string `json:"githubUsername"`
	Name           string `json:"name"`
	Email          string `json:"email"`
}
