// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Contribution struct {
	ContributionID string `json:"contributionid" bson:"contributionid"`
	ProjectName    string `json:"projectName"`
	Type           string `json:"type"`
	Date           string `json:"date"`
}

type Contributor struct {
	UserID         string          `json:"userId" bson:"_id"`
	GithubUsername string          `json:"githubUsername"`
	Name           string          `json:"name"`
	Email          string          `json:"email"`
	Contributions  []*Contribution `json:"contributions,omitempty"`
}

type NewContribution struct {
	ProjectName string `json:"projectName"`
	Type        string `json:"type"`
	Date        string `json:"date"`
}

type NewContributor struct {
	GithubUsername string           `json:"githubUsername"`
	Name           string           `json:"name"`
	Email          string           `json:"email"`
	Contributions  *NewContribution `json:"contributions,omitempty"`
}

type UpdateContributor struct {
	GithubUsername string `json:"githubUsername"`
	Name           string `json:"name"`
	Email          string `json:"email"`
}
