apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: monogodb-statefulset
  namespace: mongo
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-services
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:8.0
        ports:
        - containerPort: 27017
        startupProbe:
          exec:
            command:
              - pgrep
              - mongod
          initialDelaySeconds: 15
          periodSeconds: 5
        readinessProbe:
            exec:
              command:
                - pgrep
                - mongod
            initialDelaySeconds: 15
            periodSeconds: 5             
        livenessProbe:
          exec:
            command:
              - pgrep
              - mongod

          initialDelaySeconds: 15
          periodSeconds: 5        
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
          
  volumeClaimTemplates:
  - metadata:
      name: mongodb-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
