name: CI (Build, Format, Lint)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-format:
    name: Build and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Build
        run: go build -v ./...
      - name: Format
        run: diff <(gofmt -d .) <(echo -n)

  golangci-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: false
      - name: GolangCI-Lint Check
        uses: golangci/golangci-lint-action@v3
