name: Build and Push Image to DockerHub

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read YAML file for version
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_yaml
        with:
          config: ${{ github.workspace }}/version.yaml
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/contributors:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/contributors:${{ steps.read_yaml.outputs['version'] }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
