name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      GIN_MODE: release
    steps:
      - name: MongoDB
        uses: supercharge/mongodb-github-action@v1
        with:
          mongodb-version: '7.0'
          mongodb-port: 27017
      
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install MongoDB Database Tools
        run: sudo apt-get install -y mongodb-database-tools

      - name: Migrate database
        run: mongoimport --db test --collection contributors --file ./tests/testdata.json --jsonArray --drop

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Test
        run: go test -v ./tests/...